name: Build and Push Docker Image

on:
  repository_dispatch:
    types: [build-image]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Extract repo name without organization for Docker tag
        id: extract_repo_name
        run: |
          REPO_NAME="${{ github.event.client_payload.repo }}"
          # Extract last part after '/' for docker tag
          IMAGE_NAME="${REPO_NAME##*/}"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Checkout code from repo in payload
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.extract_repo_name.outputs.image_name }}:latest
